services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: dofus
      POSTGRES_PASSWORD: dofus
      POSTGRES_DB: dofus_admin
    ports:
      - "5432:5432"
    volumes:
      - dofus_db_data:/var/lib/postgresql/data

volumes:
  dofus_db_data:
